/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ChooseTag: typeof import('./../src/components/ChooseTag/index.vue')['default']
    FilesListShow: typeof import('./../src/components/FilesListShow/index.vue')['default']
    ImgTip: typeof import('./../src/components/ImgTip/index.vue')['default']
    InfoDivider: typeof import('./../src/components/InfoDivider/index.vue')['default']
    NavList: typeof import('./../src/components/NavList/index.vue')['default']
    PForm: typeof import('./../src/components/PVant/PForm/index.vue')['default']
    PList: typeof import('./../src/components/PList/index.vue')['default']
    PSearch: typeof import('./../src/components/PVant/PSearch/index.vue')['default']
    PVanTabs: typeof import('./../src/components/PVant/PVanTabs/index.vue')['default']
    PVantCell: typeof import('./../src/components/PVant/PVantCell/index.vue')['default']
    PVantCheckbox: typeof import('./../src/components/PVant/PVantCheckbox/index.vue')['default']
    PVantField: typeof import('./../src/components/PVant/PVantField/index.vue')['default']
    PVantRadio: typeof import('./../src/components/PVant/PVantRadio/index.vue')['default']
    PVantRate: typeof import('./../src/components/PVant/PVantRate/index.vue')['default']
    PVantSlider: typeof import('./../src/components/PVant/PVantSlider/index.vue')['default']
    PVantStepper: typeof import('./../src/components/PVant/PVantStepper/index.vue')['default']
    PVantSwitch: typeof import('./../src/components/PVant/PVantSwitch/index.vue')['default']
    ReplyDetailCard: typeof import('./../src/components/ReplyDetailCard/index.vue')['default']
    RichText: typeof import('./../src/components/RichText/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShowAh: typeof import('./../src/components/ShowAh/index.vue')['default']
    UploadFile: typeof import('./../src/components/UploadFile/index.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCalendar: typeof import('vant/es')['Calendar']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCheckbox: typeof import('vant/es')['Checkbox']
    VanDropdownItem: typeof import('vant/es')['DropdownItem']
    VanDropdownMenu: typeof import('vant/es')['DropdownMenu']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanGrid: typeof import('vant/es')['Grid']
    VanGridItem: typeof import('vant/es')['GridItem']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanList: typeof import('vant/es')['List']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPicker: typeof import('vant/es')['Picker']
    VanPopup: typeof import('vant/es')['Popup']
    VanPullRefresh: typeof import('vant/es')['PullRefresh']
    VanSearch: typeof import('vant/es')['Search']
    VanSwitch: typeof import('vant/es')['Switch']
    VanTag: typeof import('vant/es')['Tag']
    VantFieldCalendar: typeof import('./../src/components/VantForm/components/VantFieldCalendar/index.vue')['default']
    VantFieldPicker: typeof import('./../src/components/VantForm/components/VantFieldPicker/index.vue')['default']
    VantForm: typeof import('./../src/components/VantForm/index.vue')['default']
    VanTreeSelect: typeof import('vant/es')['TreeSelect']
    VanUploader: typeof import('vant/es')['Uploader']
    VanVanForm: typeof import('vant/es')['VanForm']
  }
}
